// Prisma enum type definitions
// These enums are extracted from the Prisma schema and made available
// through type definitions since the generated client is incomplete

export enum UserRole {
  STUDENT = 'STUDENT',
  ADMIN = 'ADMIN',
  SUPPORT = 'SUPPORT',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentType {
  SCHOOL_FEE = 'SCHOOL_FEE',
  ACCEPTANCE_FEE = 'ACCEPTANCE_FEE',
  HOSTEL_FEE = 'HOSTEL_FEE',
  EXAM_FEE = 'EXAM_FEE',
  NIN_REGISTRATION = 'NIN_REGISTRATION',
  JAMB_FEE = 'JAMB_FEE',
  WAEC_FEE = 'WAEC_FEE',
  NECO_FEE = 'NECO_FEE',
  OTHER_GOVERNMENT = 'OTHER_GOVERNMENT',
  UTILITY = 'UTILITY',
  LOAN_REPAYMENT = 'LOAN_REPAYMENT',
  P2P_TRANSFER = 'P2P_TRANSFER',
  WITHDRAWAL = 'WITHDRAWAL',
  WALLET_FUNDING = 'WALLET_FUNDING',
  INTERNATIONAL_REMITTANCE = 'INTERNATIONAL_REMITTANCE',
  RRR_PAYMENT = 'RRR_PAYMENT',
  CRYPTO_PAYMENT = 'CRYPTO_PAYMENT',
}

export enum PaymentMethod {
  WALLET = 'WALLET',
  CARD = 'CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  USSD = 'USSD',
  CRYPTO = 'CRYPTO',
  RRR = 'RRR',
}

export enum CryptoType {
  USDT = 'USDT',
  USDC = 'USDC',
  ETH = 'ETH',
  BTC = 'BTC',
}

export enum LoanStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DISBURSED = 'DISBURSED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  DEFAULTED = 'DEFAULTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum P2PStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum CryptoTxStatus {
  PENDING = 'PENDING',
  CONFIRMING = 'CONFIRMING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
}

export enum CryptoTxType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  PAYMENT = 'PAYMENT',
}

export enum NotificationType {
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  RECEIPT_READY = 'RECEIPT_READY',
  LOAN_APPROVED = 'LOAN_APPROVED',
  LOAN_REJECTED = 'LOAN_REJECTED',
  LOAN_DUE = 'LOAN_DUE',
  P2P_RECEIVED = 'P2P_RECEIVED',
  P2P_SENT = 'P2P_SENT',
  WALLET_CREDITED = 'WALLET_CREDITED',
  WALLET_DEBITED = 'WALLET_DEBITED',
  REMITTANCE_RECEIVED = 'REMITTANCE_RECEIVED',
  ACCOUNT_APPROVED = 'ACCOUNT_APPROVED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}

export enum RRRPaymentStatus {
  INITIATED = 'INITIATED',
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}
